import RootLayout from "@/components/Layouts/RootLayout";
import MobileMenu from "@/components/Menus/MobileMenu";
import Sidebar from "@/components/Menus/Sidebar";
import type { Metadata, NextPageContext } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <RootLayout>{children}</RootLayout>;
}

export default MainLayout;
