import MobileMenu from "@/components/Menus/MobileMenu";
import Sidebar from "@/components/Menus/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="max-w-7xl mx-auto bg-white">
      <div className="flex flex-col justify-between xs:justify-start xs:flex-row h-svh overflow-hidden relative overscroll-contain">
        <div className="hidden xs:inline md:w-1/5">
          <Sidebar />
        </div>
        <div className="flex-1 w-full lg:w-4/5 overflow-hidden">
          {children}
        </div>
        <MobileMenu />
      </div>
    </div>
  );
}

export default MainLayout;
