import type { Metadata } from "next";
import { Reddit_Mono } from "next/font/google";
import "./globals.scss";
import HTML from "@/components/HTML";

export const dynamicParams = true;
// const redditMono = local({
//   src: [],
//   variable: '--font-reddit'
// })

const poppins = Reddit_Mono({
  subsets: ["latin-ext"],
  style: "normal",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Dexa | Decentralised X",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <HTML font={poppins}>{children}</HTML>;
}
